#!/usr/bin/bash
if [ "$MCF_HOME" == "" ]; then . $HOME/.profile ; fi
vi $MCF_HOME/server.markhome.mcf/mcf-core/currentlyBrokenExCommmandForEditingSortedFilesInServerMarkhomeMcfMcfDashCore.ex $MCF_HOME/server.markhome.mcf/mcf-core/ex.cmd $MCF_HOME/server.markhome.mcf/mcf-core/src/main/java/server/markhome/mcf/sorted.files
rm -f $MCF_HOME/sorted.files
echo Copying sorted.files to $MCF_HOME/sorted.files ...
cp -v $MCF_HOME/server.markhome.mcf/mcf-core/src/main/java/server/markhome/mcf/sorted.files $MCF_HOME/sorted.files
echo Editing $MCF_HOME/sorted.files into $MCF_HOME/rename.files ...
ex $MCF_HOME/sorted.files < $MCF_HOME/server.markhome.mcf/mcf-core/ex.cmd > $MCF_HOME/rename.files
echo Viewing $MCF_HOME/sorted.files ...
cat $MCF_HOME/sorted.files
echo Viewing $MCF_HOME/rename.files ...
cat $MCF_HOME/rename.files
echo Running $MCF_HOME/rename.files ...
. $MCF_HOME/rename.files
